# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rate_limiter_pb2 as rate__limiter__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rate_limiter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RateLimiterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Acquire = channel.unary_unary(
                '/ratelimiter.RateLimiter/Acquire',
                request_serializer=rate__limiter__pb2.AcquireRequest.SerializeToString,
                response_deserializer=rate__limiter__pb2.RateLimitResponse.FromString,
                _registered_method=True)
        self.GetUsage = channel.unary_unary(
                '/ratelimiter.RateLimiter/GetUsage',
                request_serializer=rate__limiter__pb2.UsageRequest.SerializeToString,
                response_deserializer=rate__limiter__pb2.UsageResponse.FromString,
                _registered_method=True)


class RateLimiterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Acquire(self, request, context):
        """Atomically consume tokens; returns whether the request is allowed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsage(self, request, context):
        """Return sliding-window analytics without mutating buckets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateLimiterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.Acquire,
                    request_deserializer=rate__limiter__pb2.AcquireRequest.FromString,
                    response_serializer=rate__limiter__pb2.RateLimitResponse.SerializeToString,
            ),
            'GetUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsage,
                    request_deserializer=rate__limiter__pb2.UsageRequest.FromString,
                    response_serializer=rate__limiter__pb2.UsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratelimiter.RateLimiter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratelimiter.RateLimiter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RateLimiter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratelimiter.RateLimiter/Acquire',
            rate__limiter__pb2.AcquireRequest.SerializeToString,
            rate__limiter__pb2.RateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratelimiter.RateLimiter/GetUsage',
            rate__limiter__pb2.UsageRequest.SerializeToString,
            rate__limiter__pb2.UsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
