# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rate_limiter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rate_limiter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12rate_limiter.proto\x12\x0bratelimiter\"-\n\x0e\x41\x63quireRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06tokens\x18\x02 \x01(\x01\"g\n\x11RateLimitResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x18\n\x10remaining_tokens\x18\x02 \x01(\x01\x12\x14\n\x0cwindow_count\x18\x03 \x01(\x03\x12\x11\n\twindow_ms\x18\x04 \x01(\x03\"\x1b\n\x0cUsageRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"8\n\rUsageResponse\x12\x14\n\x0cwindow_count\x18\x01 \x01(\x03\x12\x11\n\twindow_ms\x18\x02 \x01(\x03\x32\x98\x01\n\x0bRateLimiter\x12\x46\n\x07\x41\x63quire\x12\x1b.ratelimiter.AcquireRequest\x1a\x1e.ratelimiter.RateLimitResponse\x12\x41\n\x08GetUsage\x12\x19.ratelimiter.UsageRequest\x1a\x1a.ratelimiter.UsageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rate_limiter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACQUIREREQUEST']._serialized_start=35
  _globals['_ACQUIREREQUEST']._serialized_end=80
  _globals['_RATELIMITRESPONSE']._serialized_start=82
  _globals['_RATELIMITRESPONSE']._serialized_end=185
  _globals['_USAGEREQUEST']._serialized_start=187
  _globals['_USAGEREQUEST']._serialized_end=214
  _globals['_USAGERESPONSE']._serialized_start=216
  _globals['_USAGERESPONSE']._serialized_end=272
  _globals['_RATELIMITER']._serialized_start=275
  _globals['_RATELIMITER']._serialized_end=427
# @@protoc_insertion_point(module_scope)
